name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publishing

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip build
        pip install setuptools wheel twine pylint

    - name: Analysing the code with pylint
      run: |
        FILES=$(git ls-files '*.py')
        if [ -n "$FILES" ]; then
          pylint $FILES
        else
          echo "No Python files found to lint."
        fi

    - name: Build the package
      run: |
        if [ -f "setup.py" ]; then
          python -m build
        else
          echo "setup.py not found. Skipping build step."
        fi
    - name: Upload to PyPI
      run: |
        twine upload dist/* -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
